import { Footer } from "./components/Footer";
import { Header } from "./components/Header";
import "./globals.css";
import { Inter } from "next/font/google";
import { Providers } from "./provider";
export const metadata = {
  title: "jackson Hotel",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="">
        <Providers>
          <Header />
          {children}
          <Footer />
          </Providers>
      </body>
    </html>
  );
}
